[package]
name = "kdotool"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.8", features = ["derive"] }
dbus = "0.9.7"
env_logger = "0.10.1"
handlebars = "4.5.0"
log = "0.4.20"
phf = { version = "0.11.2", features = ["macros"] }
serde_json = "1.0.108"
tempfile = "3.8.1"
